config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  # get 'users/new'
  devise_for :users
  unauthenticated :user do
    root to: "users#index"
  end

  authenticated :user do
    root to: "categories#index", as: :authenticated_root
  end
  resources :categories do
    resources :fundings
  end

  devise_scope  :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :fundings
  validates :name, presence: true
  def total_funds
    fundings.sum(:amount)
  end
end

app/models/funding.rb
class Funding < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :categories
  has_many :fundings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_up_path_for(_resource)
    root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @user = current_user
    @categories = current_user.categories
    # @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.create(category_params)
    if @category.save
      flash[:notice] = 'Category was successfully created.'
    else
      flash.now[:notice] = 'Failed to created'
    end
    redirect_to root_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon, :user_id)
  end
end

app/controllers/fundings_controller.rb
class FundingsController < ApplicationController
  before_action :set_funding, only: %i[show edit update destroy]

  # GET /fundings or /fundings.json
  def index
    @category = Category.find(params[:category_id])
    @fundings = @category.fundings.order(created_at: :desc)
    @total_amount = @fundings.sum(:amount)
  end

  # GET /fundings/1 or /fundings/1.json
  def show; end

  # GET /fundings/new
  def new
    # @funding = Funding.new
    @user = current_user
    @category = Category.find(params[:category_id])
    @funding = Funding.new
  end

  # GET /fundings/1/edit
  def edit; end

  # POST /fundings or /fundings.json

  def create
    @funding = Funding.new(funding_params)
    @funding.user_id = current_user.id
    @funding.category_id = Category.find_by_id(params[:category_id]).id
    respond_to do |format|
      if @funding.save
        format.html do
          redirect_to category_fundings_path(@funding.category_id), notice: 'Funding was successfully created.'
        end
        format.json { render :show, status: :created, location: @funding }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funding.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_funding
    @funding = Funding.find(params[:id])
  end

  def funding_params
    params.require(:funding).permit(:user_id, :name, :category_id, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except:
  def index; end

  def show; end

  def new; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def example_img(category)
    img_example = 'https://i.ibb.co/syp5dN2/default.png'
    if category.icon.present? and category.icon.last(4) == '.png'
      category.icon
    else
      img_example
    end
  end
end

app/helpers/fundings_helper.rb
module FundingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="name_list">
  <div class="list">
    <%= image_tag example_img(category), class: "icon-img" %>
  </div>

  <div class="list">
    <%= category.name %>
  </div>

  <div class="list">
   Total: <%= category.total_funds %> $
   </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: "Category Name" %>
  </div>

  <div>
    <%= form.text_field :icon, placeholder: "Add icon url(.png)" %>
  </div>
  <div class="create_category">
    <%= form.submit %>
  <div>
<% end %>

app/views/categories/index.html.erb
<div class="category_nav">
<h1>Categories</h1>
 <%= link_to "Logout", destroy_user_session_path, method: :delete, class:'logout_cat' %>
</div>
<div id="categories">
  <% @categories.each do |category| %>
   <a class="category_link" href = "/categories/<%= category.id %>/fundings" >
   <div class="category_list">
   <p class="user_na"><%=@user.name %></p>
    <%= render category %>
    </div>
  <% end %>
    </a>
</div>

<div class = "button_div">
<%= link_to "New category", new_category_path,class: "btn btn-success btn2" %>
</div>

app/views/categories/new.html.erb
<div class="parent">
<div class="signin_nav nav_fund">
<%= link_to "⇐",categories_path, class: "arrow" %>
<h1>New category</h1>
</div>

<%= render "form", category: @category %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/fundings/_form.html.erb
<%= form_with model: [@category, @category.fundings.create] do |form| %>
  <% if funding.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(funding.errors.count, "error") %> prohibited this funding from being saved:</h2>

      <ul>
        <% funding.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder:'Add Funding Name' %>
  </div>

  <div>
    <%= form.number_field :amount, placeholder: "Add Amount($)" %>
  </div>

  <div class="create_funding">
    <%= form.submit %>
  </div>
<% end %>

app/views/fundings/_funding.html.erb
<div id="<%= dom_id funding %>"  class="name_list" >
  <p class="list1">
    <%= funding.name %>
  </p>
  <p class="list2">
    Amount: <%= funding.amount %>$
  </p>
</div>

app/views/fundings/index.html.erb
<div class="funding_nav">
<%= link_to "⇐", categories_path, class: "arrow" %>
<h1>Fundings</h1>
</div>
<div class="category-name">
<p> <%= image_tag example_img(@category), class: "fund_img" %></p>
<p>category: <%= @category.name%> </p>
<p>Total amount: <%= @total_amount %>$ </p>
</div>

<div id="fundings">
  <% @fundings.each do |funding| %>
  <div class="funding_list">
    <%= render funding %>
    </div>
  <% end %>
</div>
<div class="button_div">
<%= link_to "New funding", new_category_funding_path(@category.id) ,class: "btn btn-success btn2"%>
</div>

app/views/fundings/new.html.erb
<div class="parent">
<div class="signin_nav nav_fund">
<%= link_to "⇐", category_fundings_path, class: "arrow" %>
<h1>New funding</h1>
</div>
<%= render "form", funding: @funding %>

</div>

app/views/fundings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @funding %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="container">
	<div class="is-flex flex-grow-1 justify-content-center align-items-center">
	  <div class="brand-logo">
        <%= image_tag("logo.jpg", :class => "home_img") %>
      </div>
	</div>
	<div class="buttons">
		<%= link_to 'Log in', new_user_session_url, class: "btn btn-success btn1" %>
		<%= link_to 'Sign up', new_user_registration_url, class: "btn btn-primary btn2" %>
	</div>
</div>